# Generated by Django 3.0.3 on 2020-04-15 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("changelogs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="github_token",
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
