# Generated by Django 2.2.4 on 2019-08-09 10:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("changelogs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="subscribers",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        )
    ]
