# Generated by Django 3.0.3 on 2020-04-16 10:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("changelogs", "0003_auto_20200416_1005"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="team",
            field=models.ManyToManyField(
                blank=True, related_name="team", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
