# Generated by Django 3.0.3 on 2020-04-21 07:48

import changelogs.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("changelogs", "0004_project_team"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="url",
            field=models.URLField(
                max_length=100, validators=[changelogs.validators.validate_project_url]
            ),
        ),
    ]
