# Generated by Django 2.2.4 on 2019-09-13 09:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("changelogs", "0004_version_project")]

    operations = [
        migrations.AddField(
            model_name="project",
            name="is_public",
            field=models.BooleanField(default=False),
        )
    ]
