# Generated by Django 3.0.3 on 2020-04-14 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("changelogs", "0005_project_is_public"),
    ]

    operations = [
        migrations.AlterModelOptions(name="project", options={"ordering": ["id"]},),
        migrations.AlterModelOptions(
            name="version", options={"ordering": ["-date_time"]},
        ),
        migrations.AlterField(
            model_name="project", name="title", field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="project", name="url", field=models.URLField(max_length=100),
        ),
    ]
